name: primer-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  # pipeline runner
  - snakemake-minimal>=8

  # taxid resolution + gene extraction + primer design
  - python=3.12
  - biopython
  - numpy
  - matplotlib-base

  # genome download
  - ncbi-genome-download

  # sequence tools
  - vsearch
  - muscle>=5
  - seqkit

  # reporting
  - markdown
